export const characters = [
    
  { id: 1, name: "alessia", image: "images/alessia.jpeg" },
 { id: 2, name: "angelo street", image: "images/angelostreet.jpeg" },
  { id: 3, name: "angiolino", image: "images/angiolino.jpeg" },
  { id: 4, name: "antonella", image: "images/antonella.jpeg" },
  { id: 5, name: "antonio maugurano", image: "images/antoniomaugurano.jpeg" },
  { id: 6, name: "bello", image: "images/bello.jpeg" },
  { id: 7, name: "benedetta", image: "images/benedetta.jpeg" },
   { id: 8, name: "benedetta castelluzzo", image: "images/benedettacastelluzzo.jpeg" },
    { id: 9, name: "calameonte", image: "images/calameonte.jpeg" },
        { id: 10, name: "caldaia", image: "images/caldaia.jpeg" },
    { id: 11, name: "carmelina", image: "images/carmelina.jpeg" },
     { id: 12, name: "mamaclo", image: "images/cavone.jpeg" },
    { id: 13, name: "coglionello", image: "images/coglionello.jpeg" },
     { id: 14, name: "cosimino baffo", image: "images/cosiminobaffo.jpeg" },
  { id: 15, name: "daniele castelluzzo", image: "images/danielecastelluzzo.jpeg" },
  { id: 16, name: "danilo", image: "images/danilo.jpeg" },
  { id: 17, name: "dario", image: "images/dario.jpeg" },
  { id: 18, name: "davide toma", image: "images/davidetoma.jpeg" },
    { id: 19, name: "diego", image: "images/diego.jpeg" },
    { id: 20, name: "diego fontò", image: "images/diegofonto.jpeg" },
    { id: 21, name: "don", image: "images/don.jpeg" },
    { id: 22, name: "elia", image: "images/elia.jpeg" },
    { id: 23, name: "enrico carcaterra", image: "images/enricocarcaterra.jpeg" },
     { id: 24, name: "enzo fontò", image: "images/enzofonto.jpeg" },
  { id: 25, name: "enzo shock", image: "images/enzoshock.jpeg" },
    { id: 26, name: "esaurito", image: "images/esaurito.jpeg" },
  { id: 27, name: "falle", image: "images/falle.jpeg" },
    { id: 28, name: "franco falle", image: "images/francofalle.jpeg" },
      { id: 29, name: "gianluca", image: "images/gianluca.jpeg" },
{ id: 30, name: "gigi", image: "images/gigi.jpeg" },
    { id: 31, name: "gigi cumpare", image: "images/gigicumpare.jpeg" },
    { id: 32, name: "gioele", image: "images/gioele.jpeg" },
{id:33,name:"gionny",image:"images/gionny.jpeg"},
     { id: 34, name: "giorgio", image: "images/giorgio.jpeg" },
{ id: 35, name: "giorgione", image: "images/giorgione.jpeg" },
     { id: 36, name: "giulia", image: "images/giulia.jpeg" },
  { id: 37, name: "giulio", image: "images/giulio.jpeg" },
  { id: 38, name: "kekko sici", image: "images/kekkosici.jpeg" },
  { id: 39, name: "lele", image: "images/lele.jpeg" },
 { id: 40, name: "leone", image: "images/leone.jpeg" },
    { id: 41, name: "limella", image: "images/limella.jpeg" },
  { id: 42, name: "lino", image: "images/lino.jpeg" },
    { id: 43, name: "luca cazzetta", image: "images/lucacazzetta.jpeg" },
{ id: 44, name: "luly", image: "images/luly.jpeg" },
    { id: 45, name: "maria rosaria", image: "images/mariarosaria.jpeg" },
    { id: 46, name: "mario", image: "images/mario.jpeg" },
     { id: 47, name: "michele", image: "images/michele.jpeg" },
  { id: 48, name: "nardio", image: "images/nardio.jpeg" },
  { id: 49, name: "orazio", image: "images/orazio.jpeg" },
    { id: 50, name: "paolo", image: "images/paolo.jpeg" },
 { id: 51, name: "pasca", image: "images/pasca.jpeg" },
  { id: 52, name: "pasqualino miggiano", image: "images/pasqualinomiggiano.jpeg" },
    { id: 53, name: "pelè", image: "images/pele.jpeg" },
    { id: 54, name: "pellmax", image: "images/pellmax.jpeg" },
    { id: 55, name: "peppefull", image: "images/peppefull.jpeg" },
    { id: 56, name: "peppe lezzi", image: "images/peppelezzi.jpeg" },
    { id: 57, name: "pinu", image: "images/pinu.jpeg" },
     { id: 58, name: "pippi scontissimo", image: "images/pippiscontissimo.jpeg" },
  { id: 59, name: "pupo", image: "images/pupo.jpeg" },
  { id: 60, name: "raffo", image: "images/raffo.jpeg" },
  { id: 61, name: "renato", image: "images/renato.jpeg" },
  { id: 62, name: "riccardo fox", image: "images/riccardofox.jpeg" },
    { id: 63, name: "rinotoma", image: "images/rinotoma.jpeg" },
    { id: 64, name: "robberto cazzetta", image: "images/robbertocazzetta.jpeg" },
    { id: 65, name: "rossano", image: "images/rossano.jpeg" },
    { id: 66, name: "sagna", image: "images/sagna.jpeg" },
    { id: 67, name: "salvatore napoletano", image: "images/salvatorenapoletano.jpeg" },
  { id:68, name: "sandropark", image: "images/sandropark.jpeg" },
{ id: 69, name: "sere", image: "images/sere.jpeg" },
{ id: 70, name: "sergio", image: "images/sergio.jpeg" },
  { id: 71, name: "simioli", image: "images/simioli.jpeg" },
  { id: 72, name: "stefano chefaccio lascio", image: "images/stefanochefacciolascio.jpeg" },
  { id: 73, name: "swami", image: "images/swami.jpeg" },
  { id: 74, name: "chapo", image: "images/tobby.jpeg" },
      { id: 75, name: "tommy", image: "images/tommy.jpeg" },
    { id: 76, name: "urpe", image: "images/urpe.jpeg" },
    { id: 77, name: "volpino", image: "images/volpino.jpeg" },
    { id: 78, name: "white", image: "images/white.jpeg" },
    { id: 79, name: "willi", image: "images/willi.jpeg" },

   
  
    
    
 
    
 
];
